### ISSUE TITLE
E exponent character missing from obs output files

### ISSUE THREAD

**Issue by christianlangevin** [MODFLOW-ORG/modflow6#809]
Several users have reported that in some cases the "E" character is not written to the OBS output files.

For example: "I noticed that the model simulates very small numbers for mass flux rather than zero away from the plume after a few iterations. When the numbers with three digit exponents are written to the list file and csv output from the obs package the ‘E’ in the number gets dropped(eg.” -2.90933775-241”, while 2 digit exponent numbers are written fine as “-2.90933775E-41”"

**Comment by jtwhite79** [comment]
@langevin-usgs thanks for looking into this! I think numbers > ~2e-308 are still "normal" WRT floating points and, for me at least, it seems its only when the exponent is negative and three digit.

**Comment by RyanConway91** [comment]
Hello, I am using the 3/2/22 nightly build and seem to be having this issue. Here are LAK concentrations I am printing:

![image](https://user-images.githubusercontent.com/25184697/156671674-4430f899-0b0e-48b7-a20a-98d1acb8b538.png)
